import MultiGame from '../components/multiGame'
import Head from 'next/head'
import { useRouter } from 'next/router'

const SinglePlayer = () => {
  const router = useRouter()
  const { slug, rounds, name } = router.query
  return (
    <>
      <Head>
        <title>Rockout</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/multiGame.css" />
      </Head>
      <main>
        <div className='bg-white text-black'>
          <h1 className='text-4xl mt-24'>Room Id: {slug}</h1>
          <h1 className='text-4xl mt-10'>Total Rounds: {rounds}</h1>
          <h1 className='text-4xl mt-10'>Player Name: {name}</h1>
        </div>
      </main>
    </>
  )
}

export default SinglePlayer