import React from 'react'
import Game from '../components/game'
import Head from 'next/head'

const SinglePlayer = () => {
  return (
    <>
      <Head>
        <title>Rockout</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/multiGame.css" />
      </Head>
      <main>
        <div className='bg-white text-black'>
          <Game />
        </div>
      </main>
    </>
  )
}

export default SinglePlayer